# Generated by Django 4.0.6 on 2022-07-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brush',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('side', models.CharField(max_length=1)),
                ('setNum', models.IntegerField()),
                ('brushStyle', models.TextField(max_length=30)),
                ('siteCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BrushComponent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brushID', models.IntegerField()),
                ('motor', models.DateField(null=True, verbose_name='%m/%d/%yyyy')),
                ('shaft', models.DateField(null=True, verbose_name='%m/%d/%yyyy')),
                ('bearings', models.DateField(null=True, verbose_name='%m/%d/%yyyy')),
                ('upperBearings', models.DateField(null=True, verbose_name='%m/%d/%yyyy')),
                ('cloth', models.DateField(null=True, verbose_name='%m/%d/%yyyy')),
                ('shocks', models.DateField(null=True, verbose_name='%m/%d/%yyyy')),
                ('siteCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('component', models.TextField(max_length=100)),
                ('dateReplaced', models.DateField(null=True, verbose_name='%m/%d/%yyyy')),
                ('dueDate', models.DateField(null=True, verbose_name='%m/%d/%yyyy')),
                ('notes', models.TextField(max_length=1000)),
                ('siteCode', models.IntegerField()),
            ],
        ),
    ]
