# Generated by Django 4.0.6 on 2022-07-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brushcomponent',
            name='bearings',
            field=models.DateField(null=True, verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AlterField(
            model_name='brushcomponent',
            name='cloth',
            field=models.DateField(null=True, verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AlterField(
            model_name='brushcomponent',
            name='motor',
            field=models.DateField(null=True, verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AlterField(
            model_name='brushcomponent',
            name='shaft',
            field=models.DateField(null=True, verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AlterField(
            model_name='brushcomponent',
            name='shocks',
            field=models.DateField(null=True, verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AlterField(
            model_name='brushcomponent',
            name='upperBearings',
            field=models.DateField(null=True, verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='dateReplaced',
            field=models.DateField(null=True, verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='dueDate',
            field=models.DateField(null=True, verbose_name='%mm/%dd/%yyyy'),
        ),
    ]
