# Generated by Django 4.0.6 on 2022-07-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_brushcomponent_bearings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='notes',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
