# Generated by Django 4.0.6 on 2022-07-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_maintenance_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('partName', models.CharField(max_length=50, null=True)),
                ('modelNumber', models.CharField(max_length=50, null=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
