# Generated by Django 4.0.6 on 2022-07-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='siteCode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
