# Generated by Django 4.0.6 on 2022-07-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='darkMode',
            field=models.BooleanField(default=False),
        ),
    ]
