# Generated by Django 4.0.6 on 2022-07-15 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='brushcomponent',
            name='bearingsReplace',
            field=models.DateField(default=datetime.date(2023, 1, 15), verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AddField(
            model_name='brushcomponent',
            name='clothReplace',
            field=models.DateField(default=datetime.date(2023, 1, 15), verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AddField(
            model_name='brushcomponent',
            name='motorReplace',
            field=models.DateField(default=datetime.date(2023, 1, 15), verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AddField(
            model_name='brushcomponent',
            name='shaftReplace',
            field=models.DateField(default=datetime.date(2023, 1, 15), verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AddField(
            model_name='brushcomponent',
            name='shocksReplace',
            field=models.DateField(default=datetime.date(2023, 1, 15), verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AddField(
            model_name='brushcomponent',
            name='upperBearingsReplace',
            field=models.DateField(default=datetime.date(2023, 1, 15), verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AlterField(
            model_name='brush',
            name='brushStyle',
            field=models.TextField(default='Enter a brush style', max_length=30),
        ),
        migrations.AlterField(
            model_name='brush',
            name='side',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='brushcomponent',
            name='bearings',
            field=models.DateField(default=datetime.date(2022, 7, 15), verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AlterField(
            model_name='brushcomponent',
            name='cloth',
            field=models.DateField(default=datetime.date(2022, 7, 15), verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AlterField(
            model_name='brushcomponent',
            name='motor',
            field=models.DateField(default=datetime.date(2022, 7, 15), verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AlterField(
            model_name='brushcomponent',
            name='shaft',
            field=models.DateField(default=datetime.date(2022, 7, 15), verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AlterField(
            model_name='brushcomponent',
            name='shocks',
            field=models.DateField(default=datetime.date(2022, 7, 15), verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AlterField(
            model_name='brushcomponent',
            name='upperBearings',
            field=models.DateField(default=datetime.date(2022, 7, 15), verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='partName',
            field=models.CharField(default='Enter a part name', max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='dateReplaced',
            field=models.DateField(default=datetime.date(2022, 7, 15), verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='dueDate',
            field=models.DateField(default=datetime.date(2023, 1, 15), verbose_name='%mm/%dd/%yyyy'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='notes',
            field=models.TextField(default='Enter notes here', max_length=1000),
        ),
    ]
