# Generated by Django 4.0.6 on 2022-07-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_brushcomponent_bearingsreplace_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brushcomponent',
            old_name='bearingsReplace',
            new_name='bearingsDueDate',
        ),
        migrations.RenameField(
            model_name='brushcomponent',
            old_name='clothReplace',
            new_name='clothDueDate',
        ),
        migrations.RenameField(
            model_name='brushcomponent',
            old_name='motorReplace',
            new_name='motorDueDate',
        ),
        migrations.RenameField(
            model_name='brushcomponent',
            old_name='shaftReplace',
            new_name='shaftDueDate',
        ),
        migrations.RenameField(
            model_name='brushcomponent',
            old_name='shocksReplace',
            new_name='shocksDueDate',
        ),
        migrations.RenameField(
            model_name='brushcomponent',
            old_name='upperBearingsReplace',
            new_name='upperBearingsDueDate',
        ),
    ]
